# Generated by Django 5.1.5 on 2025-01-28 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inv06',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcncuenta', models.IntegerField(blank=True, db_column='MCNCUENTA', null=True)),
                ('promarca', models.IntegerField(blank=True, db_column='PROMARCA', null=True)),
                ('marnombre', models.CharField(blank=True, db_column='MARNOMBRE', null=True)),
                ('mcnproduct', models.IntegerField(blank=True, db_column='MCNPRODUCT', null=True)),
                ('pronombre', models.CharField(blank=True, db_column='PRONOMBRE', null=True)),
                ('fecvence', models.CharField(blank=True, db_column='FECVENCE', null=True)),
                ('mcnbodega', models.IntegerField(blank=True, db_column='MCNBODEGA', null=True)),
                ('bodnombre', models.CharField(blank=True, db_column='BODNOMBRE', null=True)),
                ('saldo', models.IntegerField(blank=True, db_column='SALDO', null=True)),
                ('vrunit', models.FloatField(blank=True, db_column='VRUNIT', null=True)),
                ('vrtotal', models.FloatField(blank=True, db_column='VRTOTAL', null=True)),
            ],
            options={
                'db_table': 'inv06',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yyyy', models.IntegerField()),
                ('mm', models.IntegerField()),
                ('dd', models.IntegerField()),
                ('fecha', models.CharField(blank=True, max_length=50, null=True)),
                ('hora', models.CharField(blank=True, max_length=20, null=True)),
                ('clase', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo', models.CharField(blank=True, max_length=10, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('ven_cob', models.CharField(blank=True, max_length=50, null=True)),
                ('ven_cc', models.CharField(blank=True, max_length=50, null=True)),
                ('ven_nom', models.CharField(blank=True, max_length=255, null=True)),
                ('ccnit', models.CharField(blank=True, max_length=50, null=True)),
                ('cliente_nom', models.CharField(blank=True, max_length=255, null=True)),
                ('telef', models.CharField(blank=True, max_length=50, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('cliente_grp', models.CharField(blank=True, max_length=50, null=True)),
                ('cliente_grp_nom', models.CharField(blank=True, max_length=255, null=True)),
                ('ciudad_nom', models.CharField(blank=True, max_length=255, null=True)),
                ('cliente_creado', models.CharField(blank=True, max_length=50, null=True)),
                ('zona', models.CharField(blank=True, max_length=50, null=True)),
                ('zona_nom', models.CharField(blank=True, max_length=255, null=True)),
                ('bod', models.CharField(blank=True, max_length=50, null=True)),
                ('bod_nom', models.CharField(blank=True, max_length=255, null=True)),
                ('indinv', models.CharField(blank=True, max_length=10, null=True)),
                ('sku', models.CharField(blank=True, max_length=50, null=True)),
                ('umd', models.CharField(blank=True, max_length=50, null=True)),
                ('sku_nom', models.CharField(blank=True, max_length=255, null=True)),
                ('marca', models.CharField(blank=True, max_length=50, null=True)),
                ('marca_nom', models.CharField(blank=True, max_length=255, null=True)),
                ('linea', models.CharField(blank=True, max_length=50, null=True)),
                ('linea_nom', models.CharField(blank=True, max_length=255, null=True)),
                ('categ1', models.CharField(blank=True, max_length=50, null=True)),
                ('categ1_nom', models.CharField(blank=True, max_length=255, null=True)),
                ('categ2', models.CharField(blank=True, max_length=50, null=True)),
                ('categ2_nom', models.CharField(blank=True, max_length=255, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=50, null=True)),
                ('proveedor_nom', models.CharField(blank=True, max_length=255, null=True)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('listap', models.TextField(blank=True, null=True)),
                ('metodo_pago', models.CharField(blank=True, max_length=50, null=True)),
                ('iva_porc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('precio_b', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('precio_d', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('dcto1', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('iva', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('venta', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('costo_ult', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('costo_pro', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('costo_vta', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
            ],
            options={
                'db_table': 'venta_diaria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteo', models.IntegerField(blank=True, null=True)),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('diferencia', models.IntegerField(blank=True, null=True)),
                ('consolidado', models.FloatField(blank=True, default=0, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conteoApp.inv06')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'db_table': 'tarea',
            },
        ),
    ]
