# Generated by Django 5.0.6 on 2024-12-31 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inv06',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcncuenta', models.IntegerField(blank=True, db_column='MCNCUENTA', null=True)),
                ('promarca', models.IntegerField(blank=True, db_column='PROMARCA', null=True)),
                ('marnombre', models.CharField(blank=True, db_column='MARNOMBRE', null=True)),
                ('mcnproduct', models.IntegerField(blank=True, db_column='MCNPRODUCT', null=True)),
                ('pronombre', models.CharField(blank=True, db_column='PRONOMBRE', null=True)),
                ('fecvence', models.CharField(blank=True, db_column='FECVENCE', null=True)),
                ('mcnbodega', models.IntegerField(blank=True, db_column='MCNBODEGA', null=True)),
                ('bodnombre', models.CharField(blank=True, db_column='BODNOMBRE', null=True)),
                ('saldo', models.IntegerField(blank=True, db_column='SALDO', null=True)),
                ('vrunit', models.FloatField(blank=True, db_column='VRUNIT', null=True)),
                ('vrtotal', models.FloatField(blank=True, db_column='VRTOTAL', null=True)),
            ],
            options={
                'db_table': 'inv06',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcnproduct', models.CharField(blank=True, db_column='MCNPRODUCT', null=True)),
                ('marnombre', models.CharField(blank=True, db_column='MARNOMBRE', null=True)),
                ('pronombre', models.CharField(blank=True, db_column='PRONOMBRE', null=True)),
                ('mcnbodega', models.FloatField(blank=True, db_column='MCNBODEGA', null=True)),
                ('docfecha', models.DateField(blank=True, db_column='DOCFECHA', null=True)),
            ],
            options={
                'db_table': 'venta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteo', models.IntegerField(blank=True, null=True)),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('diferencia', models.IntegerField(blank=True, null=True)),
                ('consolidado', models.FloatField(blank=True, default=0, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conteoApp.inv06')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'db_table': 'tarea',
            },
        ),
    ]
