# Generated by Django 5.1.5 on 2025-03-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteoApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cta', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('marca_nom', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=50)),
                ('sku_nom', models.CharField(max_length=200)),
                ('lpt', models.CharField(max_length=8)),
                ('bod', models.CharField(max_length=10)),
                ('bod_nom', models.CharField(max_length=100)),
                ('inv_saldo', models.IntegerField(blank=True, null=True)),
                ('inv_trsto', models.IntegerField(blank=True, null=True)),
                ('vlr_unit', models.DecimalField(decimal_places=2, max_digits=20)),
                ('vlr_total', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            options={
                'db_table': 'inventario',
            },
        ),
    ]
