# Generated by Django 5.1.5 on 2025-03-19 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteoApp', '0002_inventario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conteoApp.inventario'),
        ),
    ]
