# Generated by Django 5.0.6 on 2024-11-21 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteoApp', '0002_tarea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='estado',
        ),
        migrations.AddField(
            model_name='tarea',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
