# Generated by Django 5.0.6 on 2024-11-25 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteoApp', '0003_remove_tarea_estado_tarea_observacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='diferencia',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
