# Generated by Django 5.0.6 on 2025-05-07 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteoApp', '0003_alter_tarea_producto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(choices=[('Tulua', 'Tulua'), ('Buga', 'Buga'), ('Cartago', 'Cartago'), ('Cali', 'Cali')], default='Tulua', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User City',
                'verbose_name_plural': 'User Cities',
                'db_table': 'user_city',
            },
        ),
    ]
