# Generated by Django 5.1.5 on 2025-06-10 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteoApp', '0004_usercity'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='verificado',
            field=models.BooleanField(default=False),
        ),
    ]
