# Generated by Django 5.1.5 on 2026-01-13 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteoApp', '0005_tarea_verificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='inventario',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
