# Generated by Django 5.1.5 on 2026-06-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteoApp', '0006_tarea_inventario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventario',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='tarea',
            name='tipo_bodega',
            field=models.CharField(default='almacen', max_length=20),
        ),
    ]
