# Generated by Django 5.1.5 on 2026-06-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteoApp', '0007_alter_inventario_options_tarea_tipo_bodega'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercity',
            name='bodega_asignada',
            field=models.CharField(default='almacen', max_length=20),
        ),
    ]
