# Generated by Django 5.1.15 on 2026-10-05 21:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conteoApp", "0007_alter_inventario_options_tarea_tipo_bodega_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="tarea",
            index=models.Index(
                fields=["fecha_asignacion", "tipo_bodega"], name="tarea_fecha_tipo_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tarea",
            index=models.Index(
                fields=["usuario", "fecha_asignacion"], name="tarea_usuario_fecha_idx"
            ),
        ),
    ]
