# Generated by Django 5.0.6 on 2024-12-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yyyy', models.IntegerField()),
                ('mm', models.IntegerField()),
                ('dd', models.IntegerField()),
                ('fecha', models.CharField(blank=True, max_length=50, null=True)),
                ('hora', models.CharField(blank=True, max_length=20, null=True)),
                ('clase', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo', models.CharField(blank=True, max_length=10, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('ven_cob', models.CharField(blank=True, max_length=50, null=True)),
                ('ven_cc', models.CharField(blank=True, max_length=50, null=True)),
                ('ven_nom', models.CharField(blank=True, max_length=255, null=True)),
                ('ccnit', models.CharField(blank=True, max_length=50, null=True)),
                ('cliente_nom', models.CharField(blank=True, max_length=255, null=True)),
                ('telef', models.CharField(blank=True, max_length=50, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('cliente_grp', models.CharField(blank=True, max_length=50, null=True)),
                ('cliente_grp_nom', models.CharField(blank=True, max_length=255, null=True)),
                ('ciudad_nom', models.CharField(blank=True, max_length=255, null=True)),
                ('cliente_creado', models.CharField(blank=True, max_length=50, null=True)),
                ('zona', models.CharField(blank=True, max_length=50, null=True)),
                ('zona_nom', models.CharField(blank=True, max_length=255, null=True)),
                ('bod', models.CharField(blank=True, max_length=50, null=True)),
                ('bod_nom', models.CharField(blank=True, max_length=255, null=True)),
                ('indinv', models.CharField(blank=True, max_length=10, null=True)),
                ('sku', models.CharField(blank=True, max_length=50, null=True)),
                ('umd', models.CharField(blank=True, max_length=50, null=True)),
                ('sku_nom', models.CharField(blank=True, max_length=255, null=True)),
                ('marca', models.CharField(blank=True, max_length=50, null=True)),
                ('marca_nom', models.CharField(blank=True, max_length=255, null=True)),
                ('linea', models.CharField(blank=True, max_length=50, null=True)),
                ('linea_nom', models.CharField(blank=True, max_length=255, null=True)),
                ('categ1', models.CharField(blank=True, max_length=50, null=True)),
                ('categ1_nom', models.CharField(blank=True, max_length=255, null=True)),
                ('categ2', models.CharField(blank=True, max_length=50, null=True)),
                ('categ2_nom', models.CharField(blank=True, max_length=255, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=50, null=True)),
                ('proveedor_nom', models.CharField(blank=True, max_length=255, null=True)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('listap', models.TextField(blank=True, null=True)),
                ('metodo_pago', models.CharField(blank=True, max_length=50, null=True)),
                ('iva_porc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('precio_b', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('precio_d', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('dcto1', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('iva', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('venta', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('costo_ult', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('costo_pro', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('costo_vta', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
            ],
            options={
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cta', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('marca_nom', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=50)),
                ('sku_nom', models.CharField(max_length=200)),
                ('lpt', models.CharField(max_length=8)),
                ('bod', models.CharField(max_length=10)),
                ('bod_nom', models.CharField(max_length=100)),
                ('inv_saldo', models.IntegerField(blank=True, null=True)),
                ('inv_trsto', models.IntegerField(blank=True, null=True)),
                ('vlr_unit', models.DecimalField(decimal_places=2, max_digits=20)),
                ('vlr_total', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            options={
                'db_table': 'inventario',
            },
        ),
    ]
