# Generated by Django 5.1.5 on 2025-01-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codcmc_c50', models.IntegerField(blank=True, db_column='CODCMC.C50', null=True)),
                ('producto_c15', models.IntegerField(blank=True, db_column='PRODUCTO.C15', null=True)),
                ('proveedor', models.CharField(blank=True, db_column='PROVEEDOR', null=True)),
                ('nombre_c100', models.CharField(blank=True, db_column='NOMBRE.C100', null=True)),
                ('unimed_c4', models.CharField(blank=True, db_column='UNIMED.C4', null=True)),
                ('precio_unitario_n20', models.FloatField(blank=True, db_column='PRECIO_UNITARIO.N20', null=True)),
                ('bodega_c5', models.IntegerField(blank=True, db_column='BODEGA.C5', null=True)),
                ('sede', models.CharField(blank=True, db_column='SEDE', null=True)),
                ('enero', models.IntegerField(blank=True, db_column='ENERO', null=True)),
                ('febrero', models.IntegerField(blank=True, db_column='FEBRERO', null=True)),
                ('marzo', models.IntegerField(blank=True, db_column='MARZO', null=True)),
                ('abril', models.IntegerField(blank=True, db_column='ABRIL', null=True)),
                ('mayo', models.IntegerField(blank=True, db_column='MAYO', null=True)),
                ('junio', models.IntegerField(blank=True, db_column='JUNIO', null=True)),
                ('julio', models.IntegerField(blank=True, db_column='JULIO', null=True)),
                ('agosto', models.IntegerField(blank=True, db_column='AGOSTO', null=True)),
                ('septiembre', models.IntegerField(blank=True, db_column='SEPTIEMBRE', null=True)),
                ('octubre', models.IntegerField(blank=True, db_column='OCTUBRE', null=True)),
                ('noviembre', models.IntegerField(blank=True, db_column='NOVIEMBRE', null=True)),
                ('diciembre', models.IntegerField(blank=True, db_column='DICIEMBRE', null=True)),
                ('inventario', models.IntegerField(blank=True, db_column='INVENTARIO', null=True)),
            ],
            options={
                'db_table': 'demanda',
                'managed': False,
            },
        ),
    ]
