# Generated by Django 5.0.6 on 2024-06-25 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pronosticosWebApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productos',
            options={'managed': True},
        ),
    ]
