# Generated by Django 5.1.5 on 2026-04-01 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pronosticosWebApp', '0002_demanda_leadtime_pronosticofinal_pronosticomoviln3_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'managed': False},
        ),
    ]
