# Generated by Django 5.1.5 on 2025-09-23 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuestocomercial',
            name='nombre_centro_de_operacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='presupuestocomercial',
            name='nombre_clase_cliente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
