# Generated by Django 5.1.5 on 2025-09-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuestotecnologia',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presupuestotecnologia',
            name='version',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presupuestotecnologiaaprobado',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presupuestotecnologiaaprobado',
            name='version',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
