# Generated by Django 5.1.5 on 2025-08-21 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestoApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BdPresupuestoNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_cen', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_car', models.CharField(blank=True, max_length=255, null=True)),
                ('salario', models.IntegerField(blank=True, null=True)),
                ('auxilio', models.IntegerField(blank=True, null=True)),
                ('nombre_des', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_cargo', models.CharField(blank=True, max_length=50, null=True)),
                ('valor', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bd_presupuesto_nomina',
                'managed': False,
            },
        ),
    ]
