# Generated by Django 5.1.5 on 2025-09-23 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestoApp', '0002_presupuestocomercial_nombre_centro_de_operacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuestocomercial',
            name='crecimiento',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='presupuestocomercial',
            name='proyeccion',
            field=models.BigIntegerField(default=0),
        ),
    ]
