# Generated by Django 5.1.5 on 2025-09-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestoApp', '0003_presupuestocomercial_crecimiento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presupuestocomercial',
            old_name='crecimiento',
            new_name='crecimiento_costos',
        ),
        migrations.RenameField(
            model_name='presupuestocomercial',
            old_name='proyeccion',
            new_name='crecimiento_ventas',
        ),
        migrations.AddField(
            model_name='presupuestocomercial',
            name='proyeccion_costos',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='presupuestocomercial',
            name='proyeccion_ventas',
            field=models.BigIntegerField(default=0),
        ),
    ]
