# Generated by Django 5.1.5 on 2025-09-25 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestoApp', '0004_rename_crecimiento_presupuestocomercial_crecimiento_costos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plantillagastos2025',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centro_tra', models.BigIntegerField(blank=True, db_column='CENTRO_TRA', null=True)),
                ('nombre_cen', models.CharField(blank=True, db_column='NOMBRE_CEN', null=True)),
                ('codcosto', models.BigIntegerField(blank=True, db_column='CODCOSTO', null=True)),
                ('responsable', models.CharField(blank=True, db_column='RESPONSABLE', null=True)),
                ('cuenta', models.BigIntegerField(blank=True, db_column='CUENTA', null=True)),
                ('cuenta_mayor', models.CharField(blank=True, db_column='CUENTA MAYOR', null=True)),
                ('detalle_cuenta', models.CharField(blank=True, db_column='DETALLE CUENTA', null=True)),
                ('sede_distribucion', models.FloatField(blank=True, db_column='SEDE  DISTRIBUCION', null=True)),
                ('provedor', models.CharField(blank=True, null=True)),
                ('ene', models.BigIntegerField(blank=True, null=True)),
                ('feb', models.BigIntegerField(blank=True, null=True)),
                ('mar', models.BigIntegerField(blank=True, null=True)),
                ('abr', models.FloatField(blank=True, null=True)),
                ('may', models.BigIntegerField(blank=True, null=True)),
                ('jun', models.BigIntegerField(blank=True, null=True)),
                ('jul', models.BigIntegerField(blank=True, null=True)),
                ('ago', models.FloatField(blank=True, null=True)),
                ('sep', models.FloatField(blank=True, null=True)),
                ('oct', models.FloatField(blank=True, null=True)),
                ('nov', models.FloatField(blank=True, null=True)),
                ('dic', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'plantillagastos2025',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PresupuestoTecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centro_tra', models.BigIntegerField(blank=True, null=True)),
                ('nombre_cen', models.CharField(blank=True, null=True)),
                ('codcosto', models.BigIntegerField(blank=True, null=True)),
                ('responsable', models.CharField(blank=True, null=True)),
                ('cuenta', models.BigIntegerField(blank=True, null=True)),
                ('cuenta_mayor', models.CharField(blank=True, null=True)),
                ('detalle_cuenta', models.CharField(blank=True, null=True)),
                ('sede_distribucion', models.FloatField(blank=True, null=True)),
                ('provedor', models.CharField(blank=True, null=True)),
                ('enero', models.BigIntegerField(blank=True, null=True)),
                ('febrero', models.BigIntegerField(blank=True, null=True)),
                ('marzo', models.BigIntegerField(blank=True, null=True)),
                ('abril', models.BigIntegerField(blank=True, null=True)),
                ('mayo', models.BigIntegerField(blank=True, null=True)),
                ('junio', models.BigIntegerField(blank=True, null=True)),
                ('julio', models.BigIntegerField(blank=True, null=True)),
                ('agosto', models.BigIntegerField(blank=True, null=True)),
                ('septiembre', models.BigIntegerField(blank=True, null=True)),
                ('octubre', models.BigIntegerField(blank=True, null=True)),
                ('noviembre', models.BigIntegerField(blank=True, null=True)),
                ('diciembre', models.BigIntegerField(blank=True, null=True)),
                ('total', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'presupuesto_tecnologia',
            },
        ),
        migrations.CreateModel(
            name='PresupuestoTecnologiaAux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centro_tra', models.BigIntegerField(blank=True, null=True)),
                ('nombre_cen', models.CharField(blank=True, null=True)),
                ('codcosto', models.BigIntegerField(blank=True, null=True)),
                ('responsable', models.CharField(blank=True, null=True)),
                ('cuenta', models.BigIntegerField(blank=True, null=True)),
                ('cuenta_mayor', models.CharField(blank=True, null=True)),
                ('detalle_cuenta', models.CharField(blank=True, null=True)),
                ('sede_distribucion', models.FloatField(blank=True, null=True)),
                ('provedor', models.CharField(blank=True, null=True)),
                ('enero', models.BigIntegerField(blank=True, null=True)),
                ('febrero', models.BigIntegerField(blank=True, null=True)),
                ('marzo', models.BigIntegerField(blank=True, null=True)),
                ('abril', models.BigIntegerField(blank=True, null=True)),
                ('mayo', models.BigIntegerField(blank=True, null=True)),
                ('junio', models.BigIntegerField(blank=True, null=True)),
                ('julio', models.BigIntegerField(blank=True, null=True)),
                ('agosto', models.BigIntegerField(blank=True, null=True)),
                ('septiembre', models.BigIntegerField(blank=True, null=True)),
                ('octubre', models.BigIntegerField(blank=True, null=True)),
                ('noviembre', models.BigIntegerField(blank=True, null=True)),
                ('diciembre', models.BigIntegerField(blank=True, null=True)),
                ('total', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'presupuesto_tecnologia_auxiliar',
            },
        ),
    ]
