# Generated by Django 5.1.5 on 2025-09-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestoApp', '0005_plantillagastos2025_presupuestotecnologia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BdVentas2025',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lapso', models.BigIntegerField(blank=True, db_column='Lapso', null=True)),
                ('centro_de_operacion', models.BigIntegerField(blank=True, db_column='Centro de Operacion', null=True)),
                ('nombre_centro_de_operacion', models.CharField(blank=True, db_column='Nombre Centro de Operacion', null=True)),
                ('criterio_item_1', models.FloatField(blank=True, db_column='Criterio Item 1', null=True)),
                ('nombre_criterio_item_1', models.CharField(blank=True, db_column='Nombre Criterio Item 1', null=True)),
                ('item', models.BigIntegerField(blank=True, db_column='Item', null=True)),
                ('nombre_item', models.CharField(blank=True, db_column='Nombre Item', null=True)),
                ('linea_n1', models.BigIntegerField(blank=True, db_column='Linea N1', null=True)),
                ('nombre_linea_n1', models.CharField(blank=True, db_column='Nombre Linea N1', null=True)),
                ('cliente', models.CharField(blank=True, db_column='Cliente', null=True)),
                ('nombre_cliente', models.CharField(blank=True, db_column='Nombre Cliente', null=True)),
                ('clase_cliente', models.BigIntegerField(blank=True, db_column='Clase Cliente', null=True)),
                ('nombre_clase_cliente', models.CharField(blank=True, db_column='Nombre Clase Cliente', null=True)),
                ('cantidad_1', models.FloatField(blank=True, db_column='Cantidad 1', null=True)),
                ('valor_costo', models.FloatField(blank=True, db_column='Valor Costo', null=True)),
                ('valor_neto', models.BigIntegerField(blank=True, db_column='Valor Neto', null=True)),
            ],
            options={
                'db_table': 'bd_ventas_2025',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='presupuestocentrooperacioncostos',
            name='total_year',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='presupuestocentrooperacioncostos',
            name='variacion_pct',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='presupuestocentrooperacioncostos',
            name='variacion_valor',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='presupuestocentrooperacionventas',
            name='total_year',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='presupuestocentrooperacionventas',
            name='variacion_pct',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='presupuestocentrooperacionventas',
            name='variacion_valor',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='presupuestocentrosegmentocostos',
            name='total_year',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='presupuestocentrosegmentocostos',
            name='variacion_pct',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='presupuestocentrosegmentocostos',
            name='variacion_valor',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='presupuestocentrosegmentoventas',
            name='total_year',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='presupuestocentrosegmentoventas',
            name='variacion_pct',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='presupuestocentrosegmentoventas',
            name='variacion_valor',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='presupuestocomercial',
            name='utilidad_porcentual_actual',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='presupuestocomercial',
            name='utilidad_valor_actual',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='presupuestogeneralcostos',
            name='total_year',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='presupuestogeneralcostos',
            name='variacion_pct',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='presupuestogeneralcostos',
            name='variacion_valor',
            field=models.BigIntegerField(default=0),
        ),
    ]
