# Generated by Django 5.1.5 on 2025-09-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestoApp', '0006_bdventas2025_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presupuestocentrooperacioncostos',
            name='centro_operacion',
        ),
        migrations.RemoveField(
            model_name='presupuestocentrooperacionventas',
            name='centro_operacion',
        ),
        migrations.RemoveField(
            model_name='presupuestocentrosegmentocostos',
            name='centro_operacion',
        ),
        migrations.RemoveField(
            model_name='presupuestocentrosegmentoventas',
            name='centro_operacion',
        ),
        migrations.AddField(
            model_name='presupuestocentrooperacioncostos',
            name='nombre_centro_operacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='presupuestocentrooperacionventas',
            name='nombre_centro_operacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='presupuestocentrosegmentocostos',
            name='nombre_centro_operacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='presupuestocentrosegmentoventas',
            name='nombre_centro_operacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='presupuestogeneralventas',
            name='total_year',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='presupuestogeneralventas',
            name='variacion_pct',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='presupuestogeneralventas',
            name='variacion_valor',
            field=models.BigIntegerField(default=0),
        ),
    ]
