# Generated by Django 5.1.5 on 2025-10-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestoApp', '0006_presupuestoalmacenbuga_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcncuenta', models.CharField(blank=True, db_column='MCNCUENTA', null=True)),
                ('mcnfecha', models.FloatField(blank=True, db_column='MCNFECHA', null=True)),
                ('mcntipodoc', models.CharField(blank=True, db_column='MCNTIPODOC', null=True)),
                ('mcnnumedoc', models.BigIntegerField(blank=True, db_column='MCNNUMEDOC', null=True)),
                ('mcnvincula', models.FloatField(blank=True, db_column='MCNVINCULA', null=True)),
                ('vinnombre', models.CharField(blank=True, db_column='VINNOMBRE', null=True)),
                ('mcnsucvin', models.CharField(blank=True, db_column='MCNSUCVIN', null=True)),
                ('saldoant', models.BigIntegerField(blank=True, db_column='SALDOANT', null=True)),
                ('mcnvaldebi', models.FloatField(blank=True, db_column='MCNVALDEBI', null=True)),
                ('mcnvalcred', models.FloatField(blank=True, db_column='MCNVALCRED', null=True)),
                ('saldonew', models.FloatField(blank=True, db_column='SALDONEW', null=True)),
                ('mcnsucurs', models.CharField(blank=True, db_column='MCNSUCURS', null=True)),
                ('mcnccosto', models.CharField(blank=True, db_column='MCNCCOSTO', null=True)),
                ('mcndestino', models.CharField(blank=True, db_column='MCNDESTINO', null=True)),
                ('mcndetalle', models.CharField(blank=True, db_column='MCNDETALLE', null=True)),
                ('mcnzona', models.CharField(blank=True, db_column='MCNZONA', null=True)),
                ('cconombre', models.CharField(blank=True, db_column='CCONOMBRE', null=True)),
                ('dnonombre', models.CharField(blank=True, db_column='DNONOMBRE', null=True)),
                ('zonnombre', models.CharField(blank=True, db_column='ZONNOMBRE', null=True)),
                ('mcnempresa', models.CharField(blank=True, db_column='MCNEMPRESA', null=True)),
                ('mcnclase', models.CharField(blank=True, db_column='MCNCLASE', null=True)),
                ('mcnvinkey', models.CharField(blank=True, db_column='MCNVINKEY', null=True)),
                ('tpreg', models.BigIntegerField(blank=True, db_column='TPREG', null=True)),
                ('ctanombre', models.CharField(blank=True, db_column='CTANOMBRE', null=True)),
                ('docdetalle', models.CharField(blank=True, db_column='DOCDETALLE', null=True)),
                ('infdetalle', models.CharField(blank=True, db_column='INFDETALLE', null=True)),
            ],
            options={
                'db_table': 'cuenta5',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cuenta5Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcncuenta', models.CharField(blank=True, db_column='MCNCUENTA', null=True)),
                ('mcnfecha', models.FloatField(blank=True, db_column='MCNFECHA', null=True)),
                ('mcntipodoc', models.CharField(blank=True, db_column='MCNTIPODOC', null=True)),
                ('mcnnumedoc', models.BigIntegerField(blank=True, db_column='MCNNUMEDOC', null=True)),
                ('mcnvincula', models.FloatField(blank=True, db_column='MCNVINCULA', null=True)),
                ('vinnombre', models.CharField(blank=True, db_column='VINNOMBRE', null=True)),
                ('mcnsucvin', models.CharField(blank=True, db_column='MCNSUCVIN', null=True)),
                ('saldoant', models.BigIntegerField(blank=True, db_column='SALDOANT', null=True)),
                ('mcnvaldebi', models.FloatField(blank=True, db_column='MCNVALDEBI', null=True)),
                ('mcnvalcred', models.FloatField(blank=True, db_column='MCNVALCRED', null=True)),
                ('saldonew', models.FloatField(blank=True, db_column='SALDONEW', null=True)),
                ('mcnsucurs', models.CharField(blank=True, db_column='MCNSUCURS', null=True)),
                ('mcnccosto', models.CharField(blank=True, db_column='MCNCCOSTO', null=True)),
                ('mcndestino', models.CharField(blank=True, db_column='MCNDESTINO', null=True)),
                ('mcndetalle', models.CharField(blank=True, db_column='MCNDETALLE', null=True)),
                ('mcnzona', models.CharField(blank=True, db_column='MCNZONA', null=True)),
                ('cconombre', models.CharField(blank=True, db_column='CCONOMBRE', null=True)),
                ('dnonombre', models.CharField(blank=True, db_column='DNONOMBRE', null=True)),
                ('zonnombre', models.CharField(blank=True, db_column='ZONNOMBRE', null=True)),
                ('mcnempresa', models.CharField(blank=True, db_column='MCNEMPRESA', null=True)),
                ('mcnclase', models.CharField(blank=True, db_column='MCNCLASE', null=True)),
                ('mcnvinkey', models.CharField(blank=True, db_column='MCNVINKEY', null=True)),
                ('tpreg', models.BigIntegerField(blank=True, db_column='TPREG', null=True)),
                ('ctanombre', models.CharField(blank=True, db_column='CTANOMBRE', null=True)),
                ('docdetalle', models.CharField(blank=True, db_column='DOCDETALLE', null=True)),
                ('infdetalle', models.CharField(blank=True, db_column='INFDETALLE', null=True)),
            ],
            options={
                'db_table': 'cuenta_5_base',
            },
        ),
    ]
