# Generated by Django 5.1.5 on 2025-10-21 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestoApp', '0007_cuenta5_cuenta5base'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresupuestoAuxilioTCBKITAux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=150)),
                ('centro', models.CharField(blank=True, max_length=150, null=True)),
                ('area', models.CharField(blank=True, max_length=150, null=True)),
                ('cargo', models.CharField(blank=True, max_length=150, null=True)),
                ('concepto', models.CharField(max_length=50)),
                ('enero', models.IntegerField(default=0)),
                ('febrero', models.IntegerField(default=0)),
                ('marzo', models.IntegerField(default=0)),
                ('abril', models.IntegerField(default=0)),
                ('mayo', models.IntegerField(default=0)),
                ('junio', models.IntegerField(default=0)),
                ('julio', models.IntegerField(default=0)),
                ('agosto', models.IntegerField(default=0)),
                ('septiembre', models.IntegerField(default=0)),
                ('octubre', models.IntegerField(default=0)),
                ('noviembre', models.IntegerField(default=0)),
                ('diciembre', models.IntegerField(default=0)),
                ('total', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'presupuesto_auxilio_tbckit_auxiliar',
            },
        ),
        migrations.CreateModel(
            name='PresupuestoBolsaConsumibles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=150)),
                ('centro', models.CharField(blank=True, max_length=150, null=True)),
                ('area', models.CharField(blank=True, max_length=150, null=True)),
                ('cargo', models.CharField(blank=True, max_length=150, null=True)),
                ('concepto', models.CharField(max_length=50)),
                ('enero', models.IntegerField(default=0)),
                ('febrero', models.IntegerField(default=0)),
                ('marzo', models.IntegerField(default=0)),
                ('abril', models.IntegerField(default=0)),
                ('mayo', models.IntegerField(default=0)),
                ('junio', models.IntegerField(default=0)),
                ('julio', models.IntegerField(default=0)),
                ('agosto', models.IntegerField(default=0)),
                ('septiembre', models.IntegerField(default=0)),
                ('octubre', models.IntegerField(default=0)),
                ('noviembre', models.IntegerField(default=0)),
                ('diciembre', models.IntegerField(default=0)),
                ('total', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'presupuesto_bolsa_consumibles',
            },
        ),
        migrations.CreateModel(
            name='PresupuestoBolsaConsumiblesAux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=150)),
                ('centro', models.CharField(blank=True, max_length=150, null=True)),
                ('area', models.CharField(blank=True, max_length=150, null=True)),
                ('cargo', models.CharField(blank=True, max_length=150, null=True)),
                ('concepto', models.CharField(max_length=50)),
                ('enero', models.IntegerField(default=0)),
                ('febrero', models.IntegerField(default=0)),
                ('marzo', models.IntegerField(default=0)),
                ('abril', models.IntegerField(default=0)),
                ('mayo', models.IntegerField(default=0)),
                ('junio', models.IntegerField(default=0)),
                ('julio', models.IntegerField(default=0)),
                ('agosto', models.IntegerField(default=0)),
                ('septiembre', models.IntegerField(default=0)),
                ('octubre', models.IntegerField(default=0)),
                ('noviembre', models.IntegerField(default=0)),
                ('diciembre', models.IntegerField(default=0)),
                ('total', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'presupuesto_bolsa_consumibles_auxiliar',
            },
        ),
        migrations.RenameModel(
            old_name='PresupuestoAuxilioMovilidad',
            new_name='PresupuestoAuxilioTBCKIT',
        ),
        migrations.DeleteModel(
            name='PresupuestoAuxilioMovilidadAux',
        ),
        migrations.AlterModelTable(
            name='presupuestoauxiliotbckit',
            table='presupuesto_auxilio_tbckit',
        ),
    ]
