# Generated by Django 5.1.5 on 2025-09-25 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestoApp', '0007_remove_presupuestocentrooperacioncostos_centro_operacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuestocomercial',
            name='variacion_proyetada_porcentual',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='presupuestocomercial',
            name='variacion_proyetada_valor',
            field=models.BigIntegerField(default=0),
        ),
    ]
