# Generated by Django 5.1.5 on 2025-09-25 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestoApp', '0008_presupuestocomercial_variacion_proyetada_porcentual_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presupuestocomercial',
            old_name='variacion_proyetada_porcentual',
            new_name='variacion_proyectada_porcentual',
        ),
        migrations.RenameField(
            model_name='presupuestocomercial',
            old_name='variacion_proyetada_valor',
            new_name='variacion_proyectada_valor',
        ),
    ]
