# Generated by Django 5.1.5 on 2025-11-06 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestoApp', '0008_presupuestoauxiliotcbkitaux_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuestocomercial',
            name='crecimiento_costos',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='presupuestocomercial',
            name='crecimiento_ventas',
            field=models.FloatField(default=0),
        ),
    ]
