# Generated by Django 5.1.5 on 2025-11-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestoApp', '0009_alter_presupuestocomercial_crecimiento_costos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresupuestoCentroSegLineaCostos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('nombre_centro_operacion', models.CharField(blank=True, max_length=100, null=True)),
                ('segmento', models.CharField(max_length=100)),
                ('linea', models.CharField(max_length=100)),
                ('total', models.BigIntegerField(default=0)),
                ('r2', models.FloatField(default=0)),
                ('total_year', models.BigIntegerField(default=0)),
                ('variacion_pct', models.FloatField(default=0)),
                ('variacion_valor', models.BigIntegerField(default=0)),
                ('utilidad_pct', models.FloatField(default=0)),
                ('utilidad_valor', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'presupuesto_centro_seg_linea_costos',
            },
        ),
        migrations.CreateModel(
            name='PresupuestoCentroSegLineaVentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('nombre_centro_operacion', models.CharField(blank=True, max_length=100, null=True)),
                ('segmento', models.CharField(max_length=100)),
                ('linea', models.CharField(max_length=100)),
                ('total', models.BigIntegerField(default=0)),
                ('r2', models.FloatField(default=0)),
                ('total_year', models.BigIntegerField(default=0)),
                ('total_year_costos', models.BigIntegerField(default=0)),
                ('variacion_pct', models.FloatField(default=0)),
                ('variacion_valor', models.BigIntegerField(default=0)),
                ('utilidad_pct', models.FloatField(default=0)),
                ('utilidad_valor', models.BigIntegerField(default=0)),
                ('total_proyectado', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'presupuesto_centro_seg_linea_ventas',
            },
        ),
    ]
