# Generated by Django 5.1.5 on 2025-09-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestoApp', '0009_rename_variacion_proyetada_porcentual_presupuestocomercial_variacion_proyectada_porcentual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuestocentrooperacioncostos',
            name='utilidad_pct',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='presupuestocentrooperacioncostos',
            name='utilidad_valor',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='presupuestocentrooperacionventas',
            name='utilidad_pct',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='presupuestocentrooperacionventas',
            name='utilidad_valor',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='presupuestocentrosegmentocostos',
            name='utilidad_pct',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='presupuestocentrosegmentocostos',
            name='utilidad_valor',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='presupuestocentrosegmentoventas',
            name='utilidad_pct',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='presupuestocentrosegmentoventas',
            name='utilidad_valor',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='presupuestogeneralcostos',
            name='utilidad_pct',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='presupuestogeneralcostos',
            name='utilidad_valor',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='presupuestogeneralventas',
            name='utilidad_pct',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='presupuestogeneralventas',
            name='utilidad_valor',
            field=models.BigIntegerField(default=0),
        ),
    ]
