# Generated by Django 5.1.5 on 2025-09-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestoApp', '0010_presupuestocentrooperacioncostos_utilidad_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuestocentrooperacionventas',
            name='total_year_costos',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='presupuestocentrosegmentoventas',
            name='total_year_costos',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='presupuestogeneralventas',
            name='total_year_costos',
            field=models.BigIntegerField(default=0),
        ),
    ]
