# Generated by Django 5.1.5 on 2025-12-29 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestoApp', '0010_presupuestocentroseglineacostos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsolidadoBuga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcncuenta', models.CharField(blank=True, null=True)),
                ('mcnccosto', models.CharField(blank=True, null=True)),
                ('ctanombre', models.CharField(blank=True, null=True)),
                ('mcnfecha', models.DateField(blank=True, null=True)),
                ('total_anual', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'consolidado_buga',
            },
        ),
        migrations.CreateModel(
            name='ConsolidadoCali',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcncuenta', models.CharField(blank=True, null=True)),
                ('mcnccosto', models.CharField(blank=True, null=True)),
                ('ctanombre', models.CharField(blank=True, null=True)),
                ('mcnfecha', models.DateField(blank=True, null=True)),
                ('total_anual', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'consolidado_cali',
            },
        ),
        migrations.CreateModel(
            name='ConsolidadoCartago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcncuenta', models.CharField(blank=True, null=True)),
                ('mcnccosto', models.CharField(blank=True, null=True)),
                ('ctanombre', models.CharField(blank=True, null=True)),
                ('mcnfecha', models.DateField(blank=True, null=True)),
                ('total_anual', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'consolidado_cartago',
            },
        ),
        migrations.CreateModel(
            name='ConsolidadoTotalBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcncuenta', models.CharField(blank=True, null=True)),
                ('mcnccosto', models.CharField(blank=True, null=True)),
                ('ctanombre', models.CharField(blank=True, null=True)),
                ('mcnfecha', models.DateField(blank=True, null=True)),
                ('total_anual', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'consolidado_total_base',
            },
        ),
        migrations.CreateModel(
            name='ConsolidadoTulua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcncuenta', models.CharField(blank=True, null=True)),
                ('mcnccosto', models.CharField(blank=True, null=True)),
                ('ctanombre', models.CharField(blank=True, null=True)),
                ('mcnfecha', models.DateField(blank=True, null=True)),
                ('total_anual', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'consolidado_tulua',
            },
        ),
    ]
