# Generated by Django 5.1.5 on 2025-09-26 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestoApp', '0011_presupuestocentrooperacionventas_total_year_costos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presupuestotecnologia',
            old_name='provedor',
            new_name='proveedor',
        ),
        migrations.RenameField(
            model_name='presupuestotecnologiaaux',
            old_name='provedor',
            new_name='proveedor',
        ),
    ]
