# Generated by Django 5.1.5 on 2026-05-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestoApp', '0011_consolidadototalbase'),
    ]

    operations = [
        migrations.AddField(
            model_name='consolidadototalbase',
            name='origen',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consolidadototalbase',
            name='sede',
            field=models.CharField(blank=True, null=True),
        ),
    ]
