# Generated by Django 5.1.5 on 2025-09-29 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestoApp', '0012_rename_provedor_presupuestotecnologia_proveedor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentasContables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta', models.BigIntegerField(blank=True, null=True)),
                ('nom_cuenta', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cuentas_contables',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='presupuestotecnologia',
            name='centro_tra',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presupuestotecnologia',
            name='codcosto',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presupuestotecnologiaaux',
            name='centro_tra',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presupuestotecnologiaaux',
            name='codcosto',
            field=models.CharField(blank=True, null=True),
        ),
    ]
