# Generated by Django 5.1.5 on 2026-08-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestoApp', '0013_cuenta5presupuestado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioComparativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sede', models.CharField(max_length=30)),
                ('fila_key', models.CharField(max_length=50)),
                ('mcncuenta', models.CharField(blank=True, max_length=50, null=True)),
                ('ctanombre', models.CharField(blank=True, max_length=255, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('actualizado_por', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'comparativo_comentarios',
                'unique_together': {('sede', 'fila_key')},
            },
        ),
    ]
