# Generated by Django 5.1.5 on 2025-09-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestoApp', '0013_cuentascontables_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuestotecnologia',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presupuestotecnologiaaux',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
