# Generated by Django 5.1.5 on 2026-08-11 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestoApp', '0014_comentariocomparativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcncuenta', models.CharField(max_length=60, unique=True)),
                ('ctanombre', models.CharField(blank=True, default='', max_length=255)),
                ('orden', models.PositiveIntegerField(db_index=True, default=0)),
                ('visible_total', models.BooleanField(default=True)),
                ('visible_sede', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Orden de cuenta',
                'verbose_name_plural': 'Orden de cuentas',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
