# Generated by Django 5.1.5 on 2025-09-29 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestoApp', '0014_presupuestotecnologia_comentario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresupuestotecnologiaAprobado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centro_tra', models.CharField(blank=True, null=True)),
                ('nombre_cen', models.CharField(blank=True, null=True)),
                ('codcosto', models.CharField(blank=True, null=True)),
                ('responsable', models.CharField(blank=True, null=True)),
                ('cuenta', models.BigIntegerField(blank=True, null=True)),
                ('cuenta_mayor', models.CharField(blank=True, null=True)),
                ('detalle_cuenta', models.CharField(blank=True, null=True)),
                ('sede_distribucion', models.FloatField(blank=True, null=True)),
                ('proveedor', models.CharField(blank=True, null=True)),
                ('enero', models.BigIntegerField(blank=True, null=True)),
                ('febrero', models.BigIntegerField(blank=True, null=True)),
                ('marzo', models.BigIntegerField(blank=True, null=True)),
                ('abril', models.BigIntegerField(blank=True, null=True)),
                ('mayo', models.BigIntegerField(blank=True, null=True)),
                ('junio', models.BigIntegerField(blank=True, null=True)),
                ('julio', models.BigIntegerField(blank=True, null=True)),
                ('agosto', models.BigIntegerField(blank=True, null=True)),
                ('septiembre', models.BigIntegerField(blank=True, null=True)),
                ('octubre', models.BigIntegerField(blank=True, null=True)),
                ('noviembre', models.BigIntegerField(blank=True, null=True)),
                ('diciembre', models.BigIntegerField(blank=True, null=True)),
                ('total', models.BigIntegerField(blank=True, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'presupuesto_tecnologia_aprobado',
            },
        ),
    ]
