# Generated by Django 5.1.5 on 2025-09-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestoApp', '0015_presupuestotecnologiaaprobado'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuestocentrooperacionventas',
            name='total_proyectado',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='presupuestocentrosegmentoventas',
            name='total_proyectado',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='presupuestogeneralventas',
            name='total_proyectado',
            field=models.BigIntegerField(default=0),
        ),
    ]
