# Generated by Django 5.1.5 on 2026-09-02 17:47

from django.db import migrations, models

def migrar_datos(apps, schema_editor):
    sql = """
        INSERT INTO bd_ventas_comercial (
            "Lapso", "Centro de Operacion", "Nombre Centro de Operacion",
            "Linea N1", "Nombre Linea N1", "Cliente", "Nombre Cliente",
            "Clase Cliente", "Nombre Clase Cliente", "Valor Costo", "Valor Neto"
        )
        SELECT "Lapso", "Centro de Operacion", "Nombre Centro de Operacion",
               "Linea N1", "Nombre Linea N1", "Cliente", "Nombre Cliente",
               "Clase Cliente", "Nombre Clase Cliente", "Valor Costo", "Valor Neto"
        FROM bd_ventas_2020
        UNION ALL
        SELECT "Lapso", "Centro de Operacion", "Nombre Centro de Operacion",
               "Linea N1", "Nombre Linea N1", "Cliente", "Nombre Cliente",
               "Clase Cliente", "Nombre Clase Cliente", "Valor Costo", "Valor Neto"
        FROM bd_ventas_2021
        UNION ALL
        SELECT "Lapso", "Centro de Operacion", "Nombre Centro de Operacion",
               "Linea N1", "Nombre Linea N1", "Cliente", "Nombre Cliente",
               "Clase Cliente", "Nombre Clase Cliente", "Valor Costo", "Valor Neto"
        FROM bd_ventas_2022
        UNION ALL
        SELECT "Lapso", "Centro de Operacion", "Nombre Centro de Operacion",
               "Linea N1", "Nombre Linea N1", "Cliente", "Nombre Cliente",
               "Clase Cliente", "Nombre Clase Cliente", "Valor Costo", "Valor Neto"
        FROM bd_ventas_2023
        UNION ALL
        SELECT "Lapso", "Centro de Operacion", "Nombre Centro de Operacion",
               "Linea N1", "Nombre Linea N1", "Cliente", "Nombre Cliente",
               "Clase Cliente", "Nombre Clase Cliente", "Valor Costo", "Valor Neto"
        FROM bd_ventas_2024
    """
    schema_editor.execute(sql)


def revertir(apps, schema_editor):
    schema_editor.execute("TRUNCATE TABLE bd_ventas_comercial;")
    
class Migration(migrations.Migration):

    dependencies = [
        ('presupuestoApp', '0016_cuenta4base_cuenta4presupuestado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BdVentasComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lapso', models.BigIntegerField(blank=True, db_column='Lapso', db_index=True, null=True)),
                ('centro_de_operacion', models.BigIntegerField(blank=True, db_column='Centro de Operacion', null=True)),
                ('nombre_centro_de_operacion', models.CharField(blank=True, db_column='Nombre Centro de Operacion', null=True)),
                ('linea_n1', models.BigIntegerField(blank=True, db_column='Linea N1', null=True)),
                ('nombre_linea_n1', models.CharField(blank=True, db_column='Nombre Linea N1', null=True)),
                ('cliente', models.CharField(blank=True, db_column='Cliente', null=True)),
                ('nombre_cliente', models.CharField(blank=True, db_column='Nombre Cliente', null=True)),
                ('clase_cliente', models.BigIntegerField(blank=True, db_column='Clase Cliente', null=True)),
                ('nombre_clase_cliente', models.CharField(blank=True, db_column='Nombre Clase Cliente', null=True)),
                ('valor_costo', models.FloatField(blank=True, db_column='Valor Costo', null=True)),
                ('valor_neto', models.BigIntegerField(blank=True, db_column='Valor Neto', null=True)),
            ],
            options={
                'db_table': 'bd_ventas_comercial',
                'managed': True,
                'indexes': [models.Index(fields=['lapso', 'centro_de_operacion'], name='bd_ventas_c_Lapso_373be1_idx')],
            },
        ),
        migrations.RunPython(migrar_datos, revertir),
    ]
