# Generated by Django 5.1.5 on 2026-09-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestoApp', '0016_cuenta4base_cuenta4presupuestado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BdVentasComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lapso', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('centro_de_operacion', models.BigIntegerField(blank=True, null=True)),
                ('nombre_centro_de_operacion', models.CharField(blank=True, null=True)),
                ('linea_n1', models.CharField(blank=True, null=True)),
                ('nombre_linea_n1', models.CharField(blank=True, null=True)),
                ('cliente', models.CharField(blank=True, null=True)),
                ('nombre_cliente', models.CharField(blank=True, null=True)),
                ('clase_cliente', models.CharField(blank=True, null=True)),
                ('nombre_clase_cliente', models.CharField(blank=True, null=True)),
                ('valor_costo', models.FloatField(blank=True, null=True)),
                ('valor_neto', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bd_ventas_comercial',
                'managed': True,
                'indexes': [models.Index(fields=['lapso', 'centro_de_operacion'], name='bd_ventas_c_lapso_3193b4_idx')],
            },
        ),
    ]
