# Generated by Django 5.1.5 on 2026-09-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestoApp', '0017_bdventascomercial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresupuestoNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(db_index=True, max_length=40)),
                ('cedula', models.CharField(blank=True, default='', max_length=20)),
                ('nombre', models.CharField(blank=True, default='', max_length=150)),
                ('centro', models.CharField(blank=True, default='', max_length=150)),
                ('area', models.CharField(blank=True, default='', max_length=150)),
                ('cargo', models.CharField(blank=True, default='', max_length=150)),
                ('concepto', models.CharField(blank=True, default='', max_length=80)),
                ('base', models.BigIntegerField(default=0)),
                ('factor', models.FloatField(default=1)),
                ('historico', models.JSONField(blank=True, default=dict)),
                ('enero', models.BigIntegerField(default=0)),
                ('febrero', models.BigIntegerField(default=0)),
                ('marzo', models.BigIntegerField(default=0)),
                ('abril', models.BigIntegerField(default=0)),
                ('mayo', models.BigIntegerField(default=0)),
                ('junio', models.BigIntegerField(default=0)),
                ('julio', models.BigIntegerField(default=0)),
                ('agosto', models.BigIntegerField(default=0)),
                ('septiembre', models.BigIntegerField(default=0)),
                ('octubre', models.BigIntegerField(default=0)),
                ('noviembre', models.BigIntegerField(default=0)),
                ('diciembre', models.BigIntegerField(default=0)),
                ('total', models.BigIntegerField(default=0)),
                ('origen', models.CharField(choices=[('sistema', 'Calculado'), ('manual', 'Manual')], default='manual', max_length=10)),
                ('clave', models.CharField(blank=True, default='', max_length=255)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.CharField(blank=True, default='', max_length=150)),
            ],
            options={
                'db_table': 'presupuesto_nomina',
                'ordering': ['tipo', 'id'],
                'indexes': [models.Index(fields=['tipo', 'origen'], name='nomina_tipo_origen_idx'), models.Index(fields=['tipo', 'cedula'], name='nomina_tipo_cedula_idx')],
            },
        ),
    ]
