# Generated by Django 5.1.5 on 2026-09-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestoApp', '0018_presupuestonomina'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_base', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('meses_reales', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'configuracion_nomina',
            },
        ),
        migrations.CreateModel(
            name='ConceptosNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveSmallIntegerField(db_index=True, verbose_name='año')),
                ('fecha_corte', models.DateField(blank=True, null=True, verbose_name='fecha de corte')),
                ('centro_tra', models.CharField(blank=True, default='', max_length=30)),
                ('nombre_cen', models.CharField(blank=True, default='', max_length=150)),
                ('codcosto', models.CharField(blank=True, default='', max_length=30)),
                ('nomcosto', models.CharField(blank=True, default='', max_length=150)),
                ('tipocpto', models.CharField(blank=True, default='', max_length=30)),
                ('cuenta', models.CharField(blank=True, default='', max_length=30)),
                ('concepto', models.CharField(blank=True, db_index=True, default='', max_length=30)),
                ('nombre_con', models.CharField(blank=True, default='', max_length=150)),
                ('cargo', models.CharField(blank=True, default='', max_length=30)),
                ('nombrecar', models.CharField(blank=True, default='', max_length=150)),
                ('cedula', models.BigIntegerField(blank=True, null=True)),
                ('nombre', models.CharField(blank=True, default='', max_length=150)),
                ('arlporc', models.FloatField(blank=True, null=True)),
                ('concepto_f', models.BigIntegerField(default=0)),
                ('enero', models.BigIntegerField(default=0)),
                ('febrero', models.BigIntegerField(default=0)),
                ('marzo', models.BigIntegerField(default=0)),
                ('abril', models.BigIntegerField(default=0)),
                ('mayo', models.BigIntegerField(default=0)),
                ('junio', models.BigIntegerField(default=0)),
                ('julio', models.BigIntegerField(default=0)),
                ('agosto', models.BigIntegerField(default=0)),
                ('septiembre', models.BigIntegerField(default=0)),
                ('octubre', models.BigIntegerField(default=0)),
                ('noviembre', models.BigIntegerField(default=0)),
                ('diciembre', models.BigIntegerField(default=0)),
                ('total', models.BigIntegerField(default=0)),
                ('archivo', models.CharField(blank=True, default='', max_length=255)),
                ('cargado', models.DateTimeField(auto_now_add=True)),
                ('cargado_por', models.CharField(blank=True, default='', max_length=150)),
            ],
            options={
                'verbose_name': 'concepto de nómina',
                'verbose_name_plural': 'conceptos de nómina',
                'db_table': 'conceptos_nomina',
                'indexes': [models.Index(fields=['anio', 'concepto'], name='cnomina_anio_concepto_idx'), models.Index(fields=['anio', 'cedula'], name='cnomina_anio_cedula_idx')],
            },
        ),
    ]
