# Generated by Django 5.1.5 on 2026-09-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestoApp', '0019_configuracionnomina_conceptosnomina'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuestonomina',
            name='area_origen',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='presupuestonomina',
            name='centro_origen',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.CreateModel(
            name='DistribucionNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(db_index=True, max_length=20)),
                ('centro', models.CharField(blank=True, default='', max_length=150)),
                ('area', models.CharField(max_length=150)),
                ('porcentaje', models.FloatField()),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.CharField(blank=True, default='', max_length=150)),
            ],
            options={
                'db_table': 'distribucion_nomina',
                'ordering': ['cedula', 'id'],
                'constraints': [models.UniqueConstraint(fields=('cedula', 'centro', 'area'), name='distribucion_nomina_unica')],
            },
        ),
    ]
