# Generated by Django 5.1.5 on 2026-09-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestoApp', '0020_presupuestonomina_area_origen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuestonomina',
            name='cuenta',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='presupuestonomina',
            name='excluir_de',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
