# Generated by Django 5.1.5 on 2026-09-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestoApp', '0021_presupuestonomina_cuenta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptosnomina',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de ingreso'),
        ),
    ]
