# Generated by Django 5.1.5 on 2026-09-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestoApp', '0022_conceptosnomina_fecha_ingreso'),
    ]

    operations = [
        migrations.CreateModel(
            name='FocoSinComision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(blank=True, default='', max_length=150)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.CharField(blank=True, default='', max_length=150)),
            ],
            options={
                'db_table': 'foco_sin_comision',
                'ordering': ['nombre', 'cedula'],
            },
        ),
    ]
