# Generated by Django 5.1.5 on 2026-09-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestoApp', '0023_focosincomision'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresupuestoArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=40)),
                ('etapa', models.CharField(choices=[('auxiliar', 'Auxiliar (borrador editable)'), ('proyectado', 'Proyectado (versiones subidas)'), ('aprobado', 'Aprobado')], max_length=12)),
                ('version', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('centro_tra', models.CharField(blank=True, null=True)),
                ('nombre_cen', models.CharField(blank=True, null=True)),
                ('codcosto', models.CharField(blank=True, null=True)),
                ('responsable', models.CharField(blank=True, null=True)),
                ('cuenta', models.BigIntegerField(blank=True, null=True)),
                ('cuenta_mayor', models.CharField(blank=True, null=True)),
                ('detalle_cuenta', models.CharField(blank=True, null=True)),
                ('sede_distribucion', models.FloatField(blank=True, null=True)),
                ('proveedor', models.CharField(blank=True, null=True)),
                ('enero', models.BigIntegerField(blank=True, null=True)),
                ('febrero', models.BigIntegerField(blank=True, null=True)),
                ('marzo', models.BigIntegerField(blank=True, null=True)),
                ('abril', models.BigIntegerField(blank=True, null=True)),
                ('mayo', models.BigIntegerField(blank=True, null=True)),
                ('junio', models.BigIntegerField(blank=True, null=True)),
                ('julio', models.BigIntegerField(blank=True, null=True)),
                ('agosto', models.BigIntegerField(blank=True, null=True)),
                ('septiembre', models.BigIntegerField(blank=True, null=True)),
                ('octubre', models.BigIntegerField(blank=True, null=True)),
                ('noviembre', models.BigIntegerField(blank=True, null=True)),
                ('diciembre', models.BigIntegerField(blank=True, null=True)),
                ('total', models.BigIntegerField(blank=True, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'presupuesto_area',
            },
        ),
        migrations.DeleteModel(
            name='PresupuestoAprendiz',
        ),
        migrations.DeleteModel(
            name='PresupuestoAprendizAux',
        ),
        migrations.DeleteModel(
            name='PresupuestoAuxilioEducacion',
        ),
        migrations.DeleteModel(
            name='PresupuestoAuxilioEducacionAux',
        ),
        migrations.DeleteModel(
            name='PresupuestoAuxilioTBCKIT',
        ),
        migrations.DeleteModel(
            name='PresupuestoAuxilioTCBKITAux',
        ),
        migrations.DeleteModel(
            name='PresupuestoAuxilioTransporte',
        ),
        migrations.DeleteModel(
            name='PresupuestoAuxilioTransporteAux',
        ),
        migrations.DeleteModel(
            name='PresupuestoAyudaTransporte',
        ),
        migrations.DeleteModel(
            name='PresupuestoAyudaTransporteAux',
        ),
        migrations.DeleteModel(
            name='PresupuestoBolsaConsumibles',
        ),
        migrations.DeleteModel(
            name='PresupuestoBolsaConsumiblesAux',
        ),
        migrations.DeleteModel(
            name='PresupuestoBonificaciones',
        ),
        migrations.DeleteModel(
            name='PresupuestoBonificacionesAux',
        ),
        migrations.DeleteModel(
            name='PresupuestoBonificacionesFoco',
        ),
        migrations.DeleteModel(
            name='PresupuestoBonificacionesFocoAux',
        ),
        migrations.DeleteModel(
            name='PresupuestoBonosKyrovet',
        ),
        migrations.DeleteModel(
            name='PresupuestoBonosKyrovetAux',
        ),
        migrations.DeleteModel(
            name='PresupuestoCesantias',
        ),
        migrations.DeleteModel(
            name='PresupuestoCesantiasAux',
        ),
        migrations.DeleteModel(
            name='PresupuestoComisiones',
        ),
        migrations.DeleteModel(
            name='PresupuestoComisionesAux',
        ),
        migrations.DeleteModel(
            name='PresupuestoHorasExtra',
        ),
        migrations.DeleteModel(
            name='PresupuestoHorasExtraAux',
        ),
        migrations.DeleteModel(
            name='PresupuestoInteresesCesantias',
        ),
        migrations.DeleteModel(
            name='PresupuestoInteresesCesantiasAux',
        ),
        migrations.DeleteModel(
            name='PresupuestoMediosTransporte',
        ),
        migrations.DeleteModel(
            name='PresupuestoMediosTransporteAux',
        ),
        migrations.DeleteModel(
            name='PresupuestoPrima',
        ),
        migrations.DeleteModel(
            name='PresupuestoPrimaAux',
        ),
        migrations.DeleteModel(
            name='PresupuestoSeguridadSocial',
        ),
        migrations.DeleteModel(
            name='PresupuestoSeguridadSocialAux',
        ),
        migrations.DeleteModel(
            name='PresupuestoSueldos',
        ),
        migrations.DeleteModel(
            name='PresupuestoSueldosAux',
        ),
        migrations.DeleteModel(
            name='PresupuestoVacaciones',
        ),
        migrations.DeleteModel(
            name='PresupuestoVacacionesAux',
        ),
        migrations.AddIndex(
            model_name='presupuestoarea',
            index=models.Index(fields=['area', 'etapa', 'version'], name='presup_area_etapa_ver_idx'),
        ),
    ]
