# Generated by Django 5.1.5 on 2026-09-28 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestoApp', '0026_delete_presupuestoalmacenbuga_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConceptoAuxilioEducacion',
        ),
        migrations.DeleteModel(
            name='ConceptosFijosYVariables',
        ),
    ]
