# Generated by Django 5.1.5 on 2026-09-28 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestoApp', '0027_delete_conceptoauxilioeducacion_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BdVentas2020',
        ),
        migrations.DeleteModel(
            name='BdVentas2021',
        ),
        migrations.DeleteModel(
            name='BdVentas2022',
        ),
        migrations.DeleteModel(
            name='BdVentas2023',
        ),
        migrations.DeleteModel(
            name='BdVentas2024',
        ),
        migrations.DeleteModel(
            name='BdVentas2025',
        ),
    ]
