# Generated by Django 5.1.5 on 2026-09-28 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestoApp', '0028_delete_bdventas2020_delete_bdventas2021_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                DROP TABLE IF EXISTS bd_ventas_2020;
                DROP TABLE IF EXISTS bd_ventas_2021;
                DROP TABLE IF EXISTS bd_ventas_2022;
                DROP TABLE IF EXISTS bd_ventas_2023;
                DROP TABLE IF EXISTS bd_ventas_2024;
                DROP TABLE IF EXISTS bd_ventas_2025;
                DROP TABLE IF EXISTS concepto_auxilio_educacion;
                DROP TABLE IF EXISTS conceptos_fijos_y_variables;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
