# Generated by Django 5.1.5 on 2026-09-29 16:26

# Quita el modelo Plantillagastos2025 del código. Era managed=False, así que
# NO toca la base de datos: la tabla plantillagastos2025 sigue existiendo.
# La plantilla ahora se lee por año automático (plantillagastosAAAA) en
# views_presupuesto_areas._tabla_plantilla().

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("presupuestoApp", "0030_presupuestoarea_vertical"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Plantillagastos2025",
        ),
    ]
