# Generated by Django 5.1.5 on 2026-09-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("presupuestoApp", "0031_eliminar_modelo_plantillagastos"),
    ]

    operations = [
        migrations.AddField(
            model_name="cuenta5presupuestado",
            name="comentario",
            field=models.TextField(blank=True, db_column="COMENTARIO", null=True),
        ),
        migrations.AddField(
            model_name="cuenta5presupuestado",
            name="origen_area",
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="cuenta5presupuestado",
            name="origen_subido",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cuenta5presupuestado",
            name="origen_version",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cuenta5presupuestado",
            name="responsable",
            field=models.CharField(blank=True, db_column="RESPONSABLE", null=True),
        ),
    ]
