# Generated by Django 5.1.5 on 2026-09-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("presupuestoApp", "0032_cuenta5presupuestado_comentario_responsable"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlazoEdicionArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("area", models.CharField(max_length=40, unique=True)),
                ("fecha_limite", models.DateField()),
                (
                    "actualizado_por",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                ("actualizado", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "presupuesto_plazo_edicion",
            },
        ),
    ]
