# Borra presupuesto_nomina_respaldo: la copia de la tabla horizontal de nómina
# que dejó la migración 0034 al pasar presupuesto_nomina a vertical.
#
# Reversa: vuelve a crear el respaldo VACÍO con su estructura original, para que
# la 0034 se pueda seguir revirtiendo (al revertirla, la 0034 llena el respaldo
# con los datos actuales de la tabla vertical y lo vuelve a llamar
# presupuesto_nomina). Los datos que tenía el respaldo no se recuperan.

from django.db import migrations

BORRAR = "DROP TABLE IF EXISTS presupuesto_nomina_respaldo;"

MESES = [
    "enero", "febrero", "marzo", "abril", "mayo", "junio",
    "julio", "agosto", "septiembre", "octubre", "noviembre", "diciembre",
]

RECREAR_VACIA = f"""
CREATE TABLE presupuesto_nomina_respaldo (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY
        (SEQUENCE NAME presupuesto_nomina_respaldo_id_seq),
    tipo varchar(40) NOT NULL,
    cedula varchar(20) NOT NULL,
    nombre varchar(150) NOT NULL,
    centro varchar(150) NOT NULL,
    area varchar(150) NOT NULL,
    cargo varchar(150) NOT NULL,
    concepto varchar(80) NOT NULL,
    base bigint NOT NULL,
    factor double precision NOT NULL,
    historico jsonb NOT NULL,
    {", ".join(f"{m} bigint NOT NULL" for m in MESES)},
    total bigint NOT NULL,
    origen varchar(10) NOT NULL,
    clave varchar(255) NOT NULL,
    creado timestamp with time zone NOT NULL,
    actualizado timestamp with time zone NOT NULL,
    actualizado_por varchar(150) NOT NULL,
    area_origen varchar(150) NOT NULL,
    centro_origen varchar(150) NOT NULL,
    cuenta varchar(30) NOT NULL,
    excluir_de jsonb NOT NULL,
    CONSTRAINT presupuesto_nomina_respaldo_pkey PRIMARY KEY (id)
);
CREATE INDEX resp_nomina_tipo_cedula_idx ON presupuesto_nomina_respaldo (tipo, cedula);
CREATE INDEX resp_nomina_tipo_origen_idx ON presupuesto_nomina_respaldo (tipo, origen);
CREATE INDEX resp_presupuesto_nomina_tipo_67388d3d ON presupuesto_nomina_respaldo (tipo);
CREATE INDEX resp_presupuesto_nomina_tipo_67388d3d_like
    ON presupuesto_nomina_respaldo (tipo varchar_pattern_ops);
"""


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestoApp', '0034_presupuesto_nomina_vertical'),
    ]

    operations = [
        migrations.RunSQL(BORRAR, RECREAR_VACIA),
    ]
